apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentsdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: ankushpaul210/comments
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040 # Updated to match the Dockerfile exposed port

---

apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040