apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: eventbus
          image: ankushpaul210/eventbus
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4005 # Updated to match the Dockerfile exposed port

---

apiVersion: v1
kind: Service
metadata:
  name: eventbus
spec:
  selector:
    app: eventbus
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005