apiVersion: apps/v1
kind: Deployment
metadata:
  name: querydeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: ankushpaul210/query
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001 # Updated to match the Dockerfile exposed port

---

apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001